# Generated by Django 2.2.10 on 2020-10-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
