# Generated by Django 2.2.10 on 2020-10-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0002_auto_20201011_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='offers',
        ),
    ]
