# Generated by Django 2.2.10 on 2020-10-11 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('functionality', '0003_delete_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='Requested', max_length=50)),
                ('date', models.CharField(blank=True, max_length=200)),
                ('relproperty', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='functionality.properties')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
