# Generated by Django 2.2.10 on 2020-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0004_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='date',
            new_name='requested_date',
        ),
        migrations.AddField(
            model_name='offers',
            name='closed_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offers',
            name='contract_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offers',
            name='fell_through_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offers',
            name='submitted_date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
